# Generated by Django 5.2.14 on 2026-05-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
