# Generated by Django 5.2.14 on 2026-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_payment_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='screen_name',
            field=models.CharField(default='Screen 1', max_length=50),
        ),
        migrations.AddField(
            model_name='seat',
            name='theater_name',
            field=models.CharField(default='PVR Cinemas', max_length=100),
        ),
    ]
