# Generated by Django 5.2.14 on 2026-05-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen_name',
            field=models.CharField(default='Screen 1', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='theater_name',
            field=models.CharField(default='PVR Cinemas', max_length=200),
        ),
    ]
