# Generated by Django 5.2.14 on 2026-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['genre'], name='movies_movi_genre_f96e97_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language'], name='movies_movi_languag_b4108f_idx'),
        ),
    ]
